config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  devise_scope :user do 
    delete 'user/auth/logout', to: 'omniauth_callbacks#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :search_restaurants, only: [:new]
  resources :restaurant_data_sets, only: %i[index new]
  get "/restaurant_data_sets/deleted", to: "restaurant_data_sets#destroy"
  get "/restaurant_data_sets/sent_message", to: "restaurant_data_sets#sent_message"
  get "/restaurant_data_sets/:cache_id", to: "restaurant_data_sets#show"
  get "/restaurant_data_sets/:restaurant_data_set_id/complete", to: "restaurant_data_sets#create"

  namespace :api do
    namespace :stations do
      resources :suggests, only: [:index]
    end
    post "/line/callback"
    post "/line/callback_liff"
    post "/line/send_message"
    post "validate_chat_unit", to: "validate_chat_unit#create"
    resources :custom_restaurants, only: [:create]
    resources :restaurant_data_sets, only: %i[create destroy]
    post "/restaurant_data_subsets/create_text"
  end
end

app/views/templates/_footer.html.erb
<footer class="w3-container w3-center w3-opacity" style="border-top: 1px solid orange; background-color: white; padding-top:1rem;">  
  <div class="w3-xlarge w3-padding-14">
    <a href="https://github.com/takin6/uzumeshi" target="_blank"><i class="fab fa-github fa-lg"></i></a>
 </div>
 <p>Copyright Takayuki Inoue. All rights reserved.</p>
</footer>

app/views/templates/_header.html.erb
<div class="header" id="header">
  <div class="header-logo">
    <%= link_to "Uzu Meshi", new_search_restaurant_path, class: "app-title", onclick: "onClickClearCache()" %>
    <% if restaurants %>
      <span class="total-count">検索結果：<%=restaurants.count %>件</span>
    <% end %>
  </div>

  <div class="user-menu">
    <% if user_signed_in? %>
      <% if current_user.profile_picture_url %>
        <input type="image" class="dropbtn" onclick="onClickUserMenu()" src=<%= current_user.profile_picture_url %>>
      <% else %>
        <input type="image" class="dropbtn" id="dropbtn-img" onclick="onClickUserMenu()" src="#" style="display: none" >
        <button onclick="onClickUserMenu()" class="dropbtn" id="dropbtn-nouser">
          <i class="fas fa-portrait fa-2x"></i>
        </button>
      <% end %>
    <% else %>
      <input type="image" class="dropbtn" id="dropbtn-img" onclick="onClickUserMenu()" src="#" style="display: none" >
      <button onclick="onClickUserMenu()" class="dropbtn" id="dropbtn-nouser">
        <i class="fas fa-user fa-lg" style="margin-left: 0"></i>
      </button>
    <% end %>
    <div class="user-menu-content">
      <% if user_signed_in?  %>
        <%= link_to "マイリスト", restaurant_data_sets_path %>
        <%= link_to "サインアウト", user_auth_logout_path, method: :delete, class: "delete-session-link" %>
        <a href="/">Uzu Meshiとは?</a>
      <% else %>
        <%= link_to "ログイン", user_line_omniauth_authorize_path(:bot_prompt => "aggressive",:prompt => "consent") %>
        <a href="/">Uzu Meshiとは?</a>
      <% end %>
    </div>
  </div>
</div>

app/views/templates/_paginator.html.erb
<div class="pagination-wrapper">
  <%= paginate @restaurants, params: {controller: 'restaurants', action: 'index'}, window: 1 %>
  <div>%= page_entries_info @restaurants %></div>
</div>